apiVersion: v1
kind: Service
metadata:
  name: sensor-cw-service
spec:
  selector:
    app: sensor-cw
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-cw-deployment
  labels:
    app: sensor-cw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-cw
  template:
    metadata:
      labels:
        app: sensor-cw
    spec:
      containers:
        - name: sensor-cw
          image: ecobench/sensor-cloud:latest
          ports:
            - containerPort: 8080
          envFrom:
          # The ConfigMap we want to use
          - configMapRef:
              name: sensor-cw-config
      imagePullSecrets:
        - name: github-regsecr
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-cw-config
data:
  spring.data.mongodb.host: mongodb-service
  spring.data.mongodb.port: "27017"
